version: '3.9'
services:
  beer-tracker-db:
    image: postgres
    restart: always
    container_name: beer-tracker-db
    ports:
      - 4321:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
